package com.github.derjust.spring_data_dynamodb_examples.custom;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMarshalling;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEpochDate;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;
import org.socialsignin.spring.data.dynamodb.marshaller.Instant2EpocheDynamoDBMarshaller;

import java.time.Instant;
import java.util.UUID;

@DynamoDBTable(tableName = "USER")
public class User {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey()
    private UUID id;
    private String firstname;
    private String lastname;
    @DynamoDBMarshalling(marshallerClass = Instant2EpocheDynamoDBMarshaller.class)
    private Instant birthday;
    private long age;

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public Instant getBirthday() {
        return birthday;
    }

    public void setBirthday(Instant birthday) {
        this.birthday = birthday;
    }

    public long getAge() {
        return age;
    }

    public void setAge(long age) {
        this.age = age;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", firstname='" + firstname + '\'' +
                ", lastname='" + lastname + '\'' +
                ", birthday=" + birthday +
                ", age=" + age +
                '}';
    }
}
